import type { RecruiterProjects } from '../types'

export const recruiterProjects: RecruiterProjects = {
  title: 'Projects That Show What I Build',
  description:
    'Selected systems that connect engineering capabilities to real product responsibilities, architecture, and delivery context.',
  categories: [
    { id: 'web-application', label: 'Web application' },
    { id: 'internal-system', label: 'Internal system' },
    { id: 'dashboard-reporting', label: 'Dashboard & reporting' },
    { id: 'api-integration', label: 'API & integration' },
    { id: 'internal-tool', label: 'Internal tool' },
  ],
  projects: [
    {
      id: 'ifinancing-360',
      name: 'iFinancing 360',
      type: 'Financing platform',
      categories: [
        'web-application',
        'internal-system',
        'dashboard-reporting',
        'api-integration',
      ],
      domain: 'Multifinance',
      period: {
        start: '2025-07',
        label: 'Jul 2025 - Present',
      },
      role: 'Research and Development (under CTO)',
      summary:
        'A microservice-based financing platform with dynamic dashboards, reporting, and AI-assisted analysis.',
      responsibilities: [
        'Designed and developed microservices with .NET and Blazor.',
        'Built dynamic dashboards and reporting using OpenXML.',
        'Integrated AI-assisted analysis for sentiment and data collection.',
        'Handled containerized deployment and CI/CD workflows.',
      ],
      technicalStack: [
        '.NET',
        'Blazor',
        'PostgreSQL',
        'Docker',
        'GitHub Actions',
      ],
      architecture: ['Microservices'],
      features: [
        'Dynamic dashboards',
        'Reporting with OpenXML',
        'AI-assisted analysis',
      ],
      teamContext: ['CTO', 'Development team'],
      integrations: ['AI-assisted sentiment and data collection'],
      databases: ['PostgreSQL'],
      deployment: ['Docker', 'GitHub Actions'],
      experienceIds: ['ims-research-development'],
      visualVariant: 'dashboard',
    },
    {
      id: 'ifinancing-v5',
      name: 'iFinancing v5',
      type: 'Full-stack web application',
      categories: ['web-application', 'internal-system', 'api-integration'],
      domain: 'Multifinance',
      period: {
        start: '2023-07',
        end: '2025-01',
        label: 'Jul 2023 - Jan 2025',
      },
      role: 'Full-stack Web Developer',
      summary:
        'An end-to-end multifinance platform covering more than 32 business-process modules.',
      responsibilities: [
        'Developed the frontend with Angular and consumed RESTful APIs.',
        'Built backend APIs with .NET and SQL Server.',
        'Implemented features across the complete application workflow.',
      ],
      technicalStack: [
        'Angular',
        '.NET',
        'TypeScript',
        'JavaScript',
        'SQL Server',
      ],
      architecture: ['RESTful API', 'Full-stack application'],
      features: ['End-to-end multifinance workflows'],
      teamContext: [
        'Development team',
        'QA',
        'Project leader',
        'Business team',
      ],
      integrations: ['RESTful API'],
      databases: ['SQL Server'],
      complexityIndicators: ['More than 32 business-process modules'],
      experienceIds: ['ims-fullstack'],
      visualVariant: 'workflow',
    },
    {
      id: 'si-mantap',
      name: 'Si Mantap',
      type: 'Network monitoring application',
      categories: ['web-application', 'internal-tool'],
      domain: 'Telecommunications infrastructure',
      period: {
        start: '2022-08',
        end: '2023-05',
        label: 'Aug 2022 - May 2023',
      },
      role: 'Full-stack Web Developer',
      summary:
        'A map-based network-monitoring application for ODP, OLT, cable, and tower infrastructure.',
      responsibilities: [
        'Developed map rendering with Leaflet and Firestore coordinates.',
        'Designed and built full-stack network-monitoring features.',
        'Managed related data using MongoDB.',
        'Deployed the application through Alibaba Cloud.',
      ],
      technicalStack: [
        'JavaScript',
        'Firestore',
        'MongoDB',
        'Leaflet',
        'Alibaba Cloud',
      ],
      architecture: ['Map-based monitoring', 'Full-stack application'],
      features: ['Infrastructure map rendering', 'Network monitoring'],
      teamContext: ['Regional infrastructure team'],
      databases: ['Firestore', 'MongoDB'],
      deployment: ['Alibaba Cloud'],
      experienceIds: ['telkom-regional-three'],
      visualVariant: 'map',
    },
  ],
}
