import type { ClientContent } from '../types'

export const clientContent: ClientContent = {
  identity: {
    name: '[Your name]',
    role: '[Professional role]',
    primaryCapability: '[Primary capability for client-facing work]',
    profile:
      '[Short introduction about the kind of business problems you help solve.]',
    areasOfWork: [
      '[General area of work]',
      '[Type of system or workflow]',
      '[Relevant delivery capability]',
    ],
    portrait: {
      src: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1200&q=85',
      alt: 'Temporary portrait placeholder',
    },
    location: '[Optional location]',
    links: [],
    contactInformation: '[Contact information to be added]',
    primaryAction: {
      label: "Let's discuss your project",
      href: '#client-value',
    },
  },
  valueProposition: {
    kicker: 'Client portfolio / Section 02',
    title: '[Value proposition headline]',
    highlightedTitle: '[Highlighted value]',
    description: '[Short explanation of the value delivered to clients.]',
    pillars: [
      {
        title: '[Core value pillar]',
        description: '[Why this matters to a client.]',
        icon: 'business',
      },
      {
        title: '[Delivery strength]',
        description: '[How the work is delivered.]',
        icon: 'delivery',
      },
      {
        title: '[Expected value]',
        description: '[Outcome category without unsupported metrics.]',
        icon: 'impact',
      },
    ],
    helpTitle: 'How I help your business',
    helpDescription: '[Short explanation of the delivery path.]',
    helpSteps: [
      { title: 'Understand', description: '[Template description.]' },
      { title: 'Design', description: '[Template description.]' },
      { title: 'Build', description: '[Template description.]' },
      { title: 'Deploy', description: '[Template description.]' },
      { title: 'Support', description: '[Template description.]' },
    ],
    expectationsTitle: 'What you can expect',
    expectations: [
      {
        title: '[Expected outcome]',
        description: '[Outcome description.]',
        icon: 'impact',
      },
      {
        title: '[Expected outcome]',
        description: '[Outcome description.]',
        icon: 'business',
      },
      {
        title: '[Expected outcome]',
        description: '[Outcome description.]',
        icon: 'delivery',
      },
      {
        title: '[Expected outcome]',
        description: '[Outcome description.]',
        icon: 'impact',
      },
    ],
  },
  problems: {
    kicker: 'Client portfolio / Section 03',
    title: '[Problems you help solve]',
    highlightedTitle: '[Highlighted pain point]',
    description: '[Short explanation of the business problems addressed.]',
    listTitle: 'Common challenges',
    listDescription: '[Short explanation of the problems listed below.]',
    problems: [
      {
        id: 'manual-processes',
        category: '[Problem category]',
        title: '[Manual processes]',
        situation: '[Business situation that leads to this problem.]',
        painPoint: '[Existing pain point and why it matters.]',
        icon: 'manual',
      },
      {
        id: 'data-silos',
        category: '[Problem category]',
        title: '[Data silos]',
        situation: '[Business situation that leads to this problem.]',
        painPoint: '[Existing pain point and why it matters.]',
        icon: 'data',
      },
      {
        id: 'lack-of-visibility',
        category: '[Problem category]',
        title: '[Lack of visibility]',
        situation: '[Business situation that leads to this problem.]',
        painPoint: '[Existing pain point and why it matters.]',
        icon: 'visibility',
      },
      {
        id: 'complex-workflows',
        category: '[Problem category]',
        title: '[Complex workflows]',
        situation: '[Business situation that leads to this problem.]',
        painPoint: '[Existing pain point and why it matters.]',
        icon: 'workflow',
      },
      {
        id: 'integration-issues',
        category: '[Problem category]',
        title: '[Integration issues]',
        situation: '[Business situation that leads to this problem.]',
        painPoint: '[Existing pain point and why it matters.]',
        icon: 'integration',
      },
      {
        id: 'legacy-systems',
        category: '[Problem category]',
        title: '[Legacy systems]',
        situation: '[Business situation that leads to this problem.]',
        painPoint: '[Existing pain point and why it matters.]',
        icon: 'legacy',
      },
      {
        id: 'reporting-problems',
        category: '[Problem category]',
        title: '[Reporting problems]',
        situation: '[Business situation that leads to this problem.]',
        painPoint: '[Existing pain point and why it matters.]',
        icon: 'reporting',
      },
      {
        id: 'user-experience',
        category: '[Problem category]',
        title: '[User experience]',
        situation: '[Business situation that leads to this problem.]',
        painPoint: '[Existing pain point and why it matters.]',
        icon: 'user',
      },
      {
        id: 'performance-issues',
        category: '[Problem category]',
        title: '[Performance issues]',
        situation: '[Business situation that leads to this problem.]',
        painPoint: '[Existing pain point and why it matters.]',
        icon: 'performance',
      },
      {
        id: 'security-risks',
        category: '[Problem category]',
        title: '[Security risks]',
        situation: '[Business situation that leads to this problem.]',
        painPoint: '[Existing pain point and why it matters.]',
        icon: 'security',
      },
    ],
  },
  services: {
    kicker: 'Client portfolio / Section 04',
    title: '[Services and capabilities]',
    highlightedTitle: '[Business value]',
    description: '[Short explanation of the solutions you can provide.]',
    listTitle: 'What I can help you with',
    services: [
      {
        id: 'web-application-development',
        number: '01',
        name: '[Service name]',
        category: '[Service category]',
        description: '[What this service helps a client accomplish.]',
        scope: ['[Scope item]', '[Deliverable]', '[Implementation area]'],
        applicableProblemIds: [],
        relatedProjectIds: [],
        technicalScope: [],
        businessScope: [],
        addOns: [],
        outOfScope: [],
        icon: 'web',
      },
      {
        id: 'database-design-management',
        number: '02',
        name: '[Service name]',
        category: '[Service category]',
        description: '[What this service helps a client accomplish.]',
        scope: ['[Scope item]', '[Deliverable]', '[Implementation area]'],
        applicableProblemIds: [],
        relatedProjectIds: [],
        technicalScope: [],
        businessScope: [],
        addOns: [],
        outOfScope: [],
        icon: 'database',
      },
      {
        id: 'devops-deployment',
        number: '03',
        name: '[Service name]',
        category: '[Service category]',
        description: '[What this service helps a client accomplish.]',
        scope: ['[Scope item]', '[Deliverable]', '[Implementation area]'],
        applicableProblemIds: [],
        relatedProjectIds: [],
        technicalScope: [],
        businessScope: [],
        addOns: [],
        outOfScope: [],
        icon: 'deployment',
      },
      {
        id: 'system-integration-api',
        number: '04',
        name: '[Service name]',
        category: '[Service category]',
        description: '[What this service helps a client accomplish.]',
        scope: ['[Scope item]', '[Deliverable]', '[Implementation area]'],
        applicableProblemIds: [],
        relatedProjectIds: [],
        technicalScope: [],
        businessScope: [],
        addOns: [],
        outOfScope: [],
        icon: 'integration',
      },
      {
        id: 'data-analytics-solutions',
        number: '05',
        name: '[Service name]',
        category: '[Service category]',
        description: '[What this service helps a client accomplish.]',
        scope: ['[Scope item]', '[Deliverable]', '[Implementation area]'],
        applicableProblemIds: [],
        relatedProjectIds: [],
        technicalScope: [],
        businessScope: [],
        addOns: [],
        outOfScope: [],
        icon: 'analytics',
      },
      {
        id: 'maintenance-support',
        number: '06',
        name: '[Service name]',
        category: '[Service category]',
        description: '[What this service helps a client accomplish.]',
        scope: ['[Scope item]', '[Deliverable]', '[Implementation area]'],
        applicableProblemIds: [],
        relatedProjectIds: [],
        technicalScope: [],
        businessScope: [],
        addOns: [],
        outOfScope: [],
        icon: 'support',
      },
    ],
    qualityTitle: 'Built with quality at every step',
    qualityDescription: '[Short explanation of delivery principles.]',
    qualityPrinciples: [
      {
        title: 'Secure',
        description: '[Security-oriented delivery principle.]',
        icon: 'business',
      },
      {
        title: 'Scalable',
        description: '[Scalability-oriented delivery principle.]',
        icon: 'delivery',
      },
      {
        title: 'Maintainable',
        description: '[Maintainability-oriented delivery principle.]',
        icon: 'impact',
      },
      {
        title: 'User-focused',
        description: '[User-oriented delivery principle.]',
        icon: 'business',
      },
    ],
  },
  inquiryLinks: [],
}
